### ISSUE TITLE
Missing file  /extensions/TwContextExtension.dart

### ISSUE THREAD

**Issue by filipenevola** [iamspydey/tailwind_cli#5]
Hey, I'm excited with this project :) Thank you for creating it.

I'm getting this error when trying to run my Flutter app:

```
tailwind/lib/tailwind.dart:7:1: Error: Error when reading 'tailwind/lib/extensions/TwContextExtension.dart': No such file or directory
export "./extensions/TwContextExtension.dart";
```

I'm willing to help fixing it but I don't know where to start.

**Comment by thedevsbuddy** [comment]
Hey @filipenevola,
Thanks for pointing out this issue if you can fix it and make a PR then it will be great otherwise i will fix it soon. Till you can go to the generated `tailwind` directory and in the `tailwind.dart` file just remove this line which says ` export "./extensions/TwContextExtension.dart";`.

**Comment by filipenevola** [comment]
Thanks!
